HSC-24: Added a new vaccinationswidget
mekomsolutions/bahmni-config-haiti pull request #13
Opened 2020-09-11 10:07 UTC by reagan-meant

Removed the old vaccination widget.
Added a new vaccinations widget

2020-09-14 10:40 UTC, rbuisson requested changes
- Change the label of the widget to "Vaccination summary"
- Remove the 'red' color
- Append the sequence number to the vaccine name (for reading clarity)
- In summary view, show only the most recent sequence for a given vaccine
- In extended view, show all vaccination history (incl. manufacturer, lot number...)

2020-09-14 10:40 UTC, rbuisson commented on configuration/openmrs/apps/customDisplayControl/views/immunization.html
> +                <span ng-class="{ 'is-abnormal': !obs.date}">
Let's just remove that formatting.

2020-09-14 10:40 UTC, rbuisson commented on configuration/openmrs/i18n/clinical/locale_fr.json
> +  "SEQUENCE_NUMBER": "Numéro des vaccinations.",
"Numéro de séquence"

2020-09-15 22:05 UTC, reagan-meant commented on configuration/openmrs/apps/customDisplayControl/views/immunization.html
> +                <span ng-class="{ 'is-abnormal': !obs.date}">
done

2020-09-15 22:07 UTC, reagan-meant commented on configuration/openmrs/i18n/clinical/locale_fr.json
> +  "SEQUENCE_NUMBER": "Numéro des vaccinations.",
done

2020-09-22 11:13 UTC, merged