Default french locale
mekomsolutions/bahmni-config-haiti pull request #30
Opened 2021-04-08 09:38 UTC by reagan-meant

2021-04-15 09:50 UTC, rbuisson commented on configuration/openmrs/apps/clinical/dashboard.json
> +            "header": "Patient Summary Report",
'Résumé du patient'

2021-04-15 09:57 UTC, rbuisson commented on configuration/openmrs/apps/clinical/dashboard.json
> +            "header": "Patient General Report",
'Rapport général'

2021-04-15 10:10 UTC, reagan-meant commented on configuration/openmrs/apps/clinical/dashboard.json
> +            "header": "Patient Summary Report",
Done

2021-04-15 10:14 UTC, rbuisson commented on configuration/openmrs/apps/clinical/visit.json
>              "header": "Discharge Summary",
"Synthèse de sortie"

2021-04-15 10:15 UTC, rbuisson commented on configuration/openmrs/apps/clinical/dashboard.json
> +            "header": "Patient Summary Report",
Just "Synthèse" would be good.

2021-04-15 13:07 UTC, rbuisson requested changes

2021-04-15 13:07 UTC, rbuisson commented on configuration/openmrs/apps/clinical/dashboard.json
> +                        "Historique vaccinale"
"Historique vaccinal"

2021-04-15 13:07 UTC, rbuisson commented on configuration/openmrs/apps/clinical/dashboard.json
> +                        "Clief Complaint Notes",
Clief?

2021-04-15 13:34 UTC, reagan-meant commented on configuration/openmrs/apps/clinical/dashboard.json
> +                        "Historique vaccinale"
Done

2021-04-15 13:35 UTC, reagan-meant commented on configuration/openmrs/apps/clinical/dashboard.json
> +                        "Clief Complaint Notes",
These must have been from form one...

2021-04-16 09:40 UTC, rbuisson approved these changes

2021-04-16 09:42 UTC, merged